In [1]:
import pandas as pd
import altair as alt

In [2]:
df = pd.read_csv("ca_fire.csv")

In [3]:
df

,OBJECTID,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,...,OBJECTIVE,GIS_ACRES,COMMENTS,COMPLEX_NAME,COMPLEX_INCNUM,IRWINID,FIRE_NUM,DECADES,SHAPE_Length,SHAPE_Area
0,21440,2020.0,CA,CDF,NEU,NELSON,00013212,2020/06/18 00:00:00+00,2020/06/23 00:00:00+00,11.0,...,1.0,109.602280,NaN,NaN,NaN,NaN,NaN,2020.0,4179.743142,7.331347e+05
1,21441,2020.0,CA,CDF,NEU,AMORUSO,00011799,2020/06/01 00:00:00+00,2020/06/04 00:00:00+00,2.0,...,1.0,685.585020,NaN,NaN,NaN,NaN,NaN,2020.0,12399.375391,4.578172e+06
2,21442,2020.0,CA,CDF,NEU,ATHENS,00018493,2020/08/10 00:00:00+00,2020/08/11 00:00:00+00,14.0,...,1.0,27.300480,NaN,NaN,NaN,NaN,NaN,2020.0,2119.194120,1.823876e+05
3,21443,2020.0,CA,CDF,NEU,FLEMING,00007619,2020/03/31 00:00:00+00,2020/04/01 00:00:00+00,9.0,...,1.0,12.931545,NaN,NaN,NaN,NaN,NaN,2020.0,2029.524881,8.667942e+04
4,21444,2020.0,CA,CDF,NEU,MELANESE,00008471,2020/04/14 00:00:00+00,2020/04/19 00:00:00+00,18.0,...,1.0,10.315964,NaN,NaN,NaN,NaN,NaN,2020.0,1342.742903,7.017912e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21921,43907,2022.0,CA,LRA,VNC,CHAMBERS,00023419,2022/03/16 00:00:00+00,2022/03/17 00:00:00+00,14.0,...,1.0,1.547286,NaN,NaN,NaN,B541FD2D-0474-47CF-AF6C-C4576E03A590,NaN,2020.0,537.691347,9.217709e+03
21922,43908,2022.0,CA,LRA,VNC,MOON,00073287,2022/08/14 00:00:00+00,2022/08/14 00:00:00+00,14.0,...,1.0,1.424808,NaN,NaN,NaN,EE538AD9-C557-40F2-9EDD-56C345B4E7FD,NaN,2020.0,452.799309,8.444197e+03
21923,43909,2022.0,CA,USF,SHF,TEXAS,00000953,2022/09/09 00:00:00+00,2022/09/10 00:00:00+00,14.0,...,1.0,12.912493,BA5FDCF1-23D0-43FD-8DA9-3FF21A5C0F81,NaN,NaN,BA5FDCF1-23D0-43FD-8DA9-3FF21A5C0F81,NaN,2020.0,2061.550880,8.985026e+04
21924,43910,2022.0,CA,USF,KNF,ALEX,00006290,2022/07/31 00:00:00+00,2022/08/03 00:00:00+00,14.0,...,1.0,150.403530,E9A30E52-C8E6-4AA5-B7D8-967923865340,NaN,NaN,E9A30E52-C8E6-4AA5-B7D8-967923865340,NaN,2020.0,6500.414625,1.100802e+06
21925,43911,2022.0,CA,CDF,TGU,TULARE,00008878,2022/07/25 00:00:00+00,2022/07/25 00:00:00+00,10.0,...,1.0,134.469820,NaN,NaN,NaN,0269DB87-31A2-4DDE-BAB4-74092225EF4E,NaN,2020.0,5645.738468,9.290376e+05

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21926 entries, 0 to 21925
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBJECTID        21926 non-null  int64
 1   YEAR_           21849 non-null  float64
 2   STATE           21926 non-null  object
 3   AGENCY          21921 non-null  object
 4   UNIT_ID         21907 non-null  object
 5   FIRE_NAME       21802 non-null  object
 6   INC_NUM         21002 non-null  object
 7   ALARM_DATE      16578 non-null  object
 8   CONT_DATE       9346 non-null   object
 9   CAUSE           21902 non-null  float64
 10  C_METHOD        9805 non-null   float64
 11  OBJECTIVE       21732 non-null  float64
 12  GIS_ACRES       21926 non-null  float64
 13  COMMENTS        4102 non-null   object
 14  COMPLEX_NAME    571 non-null    object
 15  COMPLEX_INCNUM  534 non-null    object
 16  IRWINID         332 non-null    object
 17  FIRE_NUM        17201 non-null  object
 18  DECADES         16704 non-null  float64
 19  SHAPE_Length    21926 non-null  float64
 20  SHAPE_Area      21926 non-null  float64
dtypes: float64(8), int64(1), object(12)
memory usage: 3.5+ MB

In [27]:
df2 = df.dropna(thresh=10000, axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21926 entries, 0 to 21925
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OBJECTID      21926 non-null  int64
 1   YEAR_         21849 non-null  float64
 2   STATE         21926 non-null  object
 3   AGENCY        21921 non-null  object
 4   UNIT_ID       21907 non-null  object
 5   FIRE_NAME     21802 non-null  object
 6   INC_NUM       21002 non-null  object
 7   ALARM_DATE    16578 non-null  object
 8   CAUSE         21902 non-null  float64
 9   OBJECTIVE     21732 non-null  float64
 10  GIS_ACRES     21926 non-null  float64
 11  FIRE_NUM      17201 non-null  object
 12  DECADES       16704 non-null  float64
 13  SHAPE_Length  21926 non-null  float64
 14  SHAPE_Area    21926 non-null  float64
dtypes: float64(7), int64(1), object(7)
memory usage: 2.5+ MB

In [32]:
df2.drop(columns=["INC_NUM", "ALARM_DATE", "OBJECTIVE", "GIS_ACRES"]).dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 12060 entries, 489 to 21569
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OBJECTID      12060 non-null  int64
 1   YEAR_         12060 non-null  float64
 2   STATE         12060 non-null  object
 3   AGENCY        12060 non-null  object
 4   UNIT_ID       12060 non-null  object
 5   FIRE_NAME     12060 non-null  object
 6   CAUSE         12060 non-null  float64
 7   FIRE_NUM      12060 non-null  object
 8   DECADES       12060 non-null  float64
 9   SHAPE_Length  12060 non-null  float64
 10  SHAPE_Area    12060 non-null  float64
dtypes: float64(5), int64(1), object(5)
memory usage: 1.1+ MB